// ORDER_SERVICE
export const ORDER_SERVICE = "ORDER_SERVICE";

// PRODUCTS_SERVICE
export const PRODUCTS_SERVICE = "PRODUCTS_SERVICE";

// AUTH_SERVICE
export const AUTH_SERVICE = "AUTH_SERVICE";

// AUTH_SERVICE
export const PUNKT_SERVICE = "PUNKT_SERVICE";
